version: "3.3"

volumes:
  pg:
  redis:

services:

  postgres:
    image: postgres:alpine
    container_name: postgres
    ports:
      - "${PG_PORT}:${PG_PORT}"
    restart: always
    env_file:
      - prod.env
    environment:
      POSTGRES_DB: "${PG_NAME}"
      POSTGRES_USER: "${PG_USER}"
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
    volumes:
      - ./deploy/db/01_init.up.sql:/docker-entrypoint-initdb.d/init.sql
      - pg:/var/lib/postgresql/data

  # redis-overcommit-on-host
  redis-overcommit:
    build: https://github.com/bkuhl/redis-overcommit-on-host.git
    restart: 'no'
    privileged: true
    volumes:
      - /proc/sys/vm:/mnt/vm

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    restart: always
    env_file:
      - prod.env
    depends_on:
      - redis-overcommit
    volumes:
      - redis:/data

  tonflow:
    image: tonflow
    container_name: tonflow
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: on-failure
    env_file:
      - prod.env